function draft(article) {
  return { ...article, status: 'draft', schemaType: 'Article' };
}

const ARTICLES = [
  draft({
    slug: 'cuanto-cuesta-pagina-web-catamarca',
    path: '/blog/cuanto-cuesta-pagina-web-catamarca',
    title: '¿Cuánto cuesta una página web en Catamarca?',
    description: 'Qué variables influyen en el costo de una página web para un negocio de Catamarca.',
    quickAnswer: 'No existe un precio único. El costo depende del alcance, el contenido, las integraciones y el nivel de mantenimiento que necesite el negocio.',
    sections: [
      { heading: 'Qué se debe definir antes de hablar de precio', paragraphs: ['La cantidad de páginas, el tipo de contenido, el formulario, las integraciones y la forma de actualizar el sitio cambian el alcance del trabajo.'] },
      { heading: 'Ejemplo de alcance', paragraphs: ['Una landing para presentar un servicio no tiene las mismas necesidades que un sitio con catálogo, reservas o panel de administración.'] },
    ],
    example: 'Comparar una landing, un sitio institucional y una tienda ayuda a detectar qué funciones son realmente necesarias.',
    faq: [{ question: '¿Se puede recibir un presupuesto cerrado?', answer: 'Sí, después de revisar el alcance y la información disponible del proyecto.' }],
    links: [{ href: '/desarrollo-web-catamarca', label: 'Desarrollo web en Catamarca' }, { href: '/contacto', label: 'Consultar un proyecto' }],
    cta: { href: '/contacto', label: 'Consultar alcance' },
  }),
  draft({
    slug: 'cuanto-cuesta-pagina-web-argentina',
    path: '/blog/cuanto-cuesta-pagina-web-argentina',
    title: '¿Cuánto cuesta hacer una página web en Argentina?',
    description: 'Guía para entender qué incluye el precio de una página web en Argentina sin comparar solo números.',
    quickAnswer: 'El precio depende más del alcance que de una tarifa universal: estructura, contenido, funcionalidades, soporte e integraciones son las variables principales.',
    sections: [
      { heading: 'No comparar propuestas por el número solamente', paragraphs: ['Dos presupuestos pueden tener importes distintos porque incluyen entregables, tiempos de trabajo o mantenimiento diferentes.'] },
      { heading: 'Qué preguntar en una propuesta', paragraphs: ['Conviene revisar qué páginas se entregan, quién prepara el contenido, qué cambios están incluidos y qué ocurre después de publicar.'] },
    ],
    example: 'Una propuesta que incluye solo una página no se puede comparar directamente con otra que contempla catálogo, formularios y administración.',
    faq: [{ question: '¿Qué debe aclarar un presupuesto?', answer: 'El alcance, los entregables, las responsabilidades y las condiciones de mantenimiento.' }],
    links: [{ href: '/desarrollo-web', label: 'Ver desarrollo web' }, { href: '/blog/cuanto-cuesta-pagina-web-catamarca', label: 'Costo en Catamarca' }],
    cta: { href: '/contacto', label: 'Revisar un proyecto' },
  }),
  draft({
    slug: 'cuanto-demora-crear-pagina-web',
    path: '/blog/cuanto-demora-crear-pagina-web',
    title: '¿Cuánto demora crear una página web?',
    description: 'Qué factores afectan el tiempo de desarrollo de una página web y cómo organizar el proyecto.',
    quickAnswer: 'El tiempo depende del tamaño del sitio, la disponibilidad del contenido, las revisiones y las integraciones necesarias.',
    sections: [
      { heading: 'El contenido también forma parte del calendario', paragraphs: ['Cuando faltan textos, fotos o decisiones sobre el alcance, el trabajo se detiene aunque el código esté listo.'] },
      { heading: 'Trabajar por etapas', paragraphs: ['Definir una primera versión concreta permite publicar una base útil y dejar mejoras para una etapa posterior.'] },
    ],
    example: 'Una landing con contenido listo puede avanzar de forma distinta que un sitio que necesita definir catálogo, textos y formularios desde cero.',
    faq: [{ question: '¿Se puede acordar una fecha?', answer: 'Sí, cuando el alcance y los insumos del proyecto están suficientemente claros.' }],
    links: [{ href: '/desarrollo-web', label: 'Desarrollo web' }, { href: '/contacto', label: 'Hablar del calendario' }],
    cta: { href: '/contacto', label: 'Planificar una primera etapa' },
  }),
  draft({
    slug: 'pagina-web-vs-redes-sociales',
    path: '/blog/pagina-web-vs-redes-sociales',
    title: 'Página web vs. redes sociales: qué necesita un negocio',
    description: 'Diferencias entre tener una página web y usar redes sociales para comunicar un negocio.',
    quickAnswer: 'No cumplen la misma función: las redes ayudan a conversar y descubrir; una web ordena la información y ofrece un lugar propio.',
    sections: [
      { heading: 'Qué aportan las redes', paragraphs: ['Las redes sirven para publicar novedades, mostrar el día a día y mantener conversaciones frecuentes con una comunidad.'] },
      { heading: 'Qué aporta una web', paragraphs: ['Una página permite organizar servicios, preguntas frecuentes, contacto y contenido sin depender de un único feed.'] },
    ],
    example: 'Un restaurante puede usar redes para mostrar platos y una web para centralizar menú, ubicación, reservas y horarios confirmados.',
    faq: [{ question: '¿Hay que elegir una sola opción?', answer: 'No. Una web y las redes pueden complementarse con enlaces y mensajes coherentes.' }],
    links: [{ href: '/desarrollo-web', label: 'Ver desarrollo web' }, { href: '/contacto', label: 'Consultar una web' }],
    cta: { href: '/contacto', label: 'Ordenar la presencia online' },
  }),
  draft({
    slug: 'que-necesita-una-empresa-para-tener-pagina-web',
    path: '/blog/que-necesita-una-empresa-para-tener-pagina-web',
    title: '¿Qué necesita una empresa para tener una página web?',
    description: 'Checklist simple de información y decisiones para empezar un proyecto web.',
    quickAnswer: 'Necesita un objetivo claro, información del negocio, contenido básico, un canal de contacto y una definición inicial del alcance.',
    sections: [
      { heading: 'Información que conviene reunir', paragraphs: ['Nombre, propuesta, servicios, preguntas frecuentes, datos de contacto y material visual ayudan a comenzar con una base concreta.'] },
      { heading: 'Decisiones que pueden esperar', paragraphs: ['No hace falta resolver todo el crecimiento futuro antes de publicar una primera versión. Se puede priorizar lo importante para la etapa actual.'] },
    ],
    example: 'Una empresa puede empezar con sus tres servicios principales y ampliar la web cuando tenga nuevas preguntas o productos.',
    faq: [{ question: '¿Hay que tener todo el contenido listo?', answer: 'No necesariamente, pero sí conviene definir qué información es imprescindible para la primera versión.' }],
    links: [{ href: '/desarrollo-web', label: 'Desarrollo web' }, { href: '/contacto', label: 'Consultar requisitos' }],
    cta: { href: '/contacto', label: 'Preparar una primera versión' },
  }),
  draft({
    slug: 'cuanto-cuesta-tienda-online',
    path: '/blog/cuanto-cuesta-tienda-online',
    title: '¿Cuánto cuesta una tienda online?',
    description: 'Qué componentes forman el alcance y el costo de una tienda online.',
    quickAnswer: 'El costo depende del catálogo, las variantes, los pedidos, los cobros, la entrega y la administración que necesite el negocio.',
    sections: [
      { heading: 'Una tienda es más que un catálogo', paragraphs: ['Además de mostrar productos hay que definir cómo se consulta, se compra, se paga, se entrega y se actualiza la información.'] },
      { heading: 'Empezar por lo que se va a usar', paragraphs: ['Reducir el alcance inicial puede ayudar a validar el canal antes de sumar automatizaciones o integraciones.'] },
    ],
    example: 'Una tienda de pocos productos puede comenzar con catálogo y consulta, mientras otra necesita variantes, stock y flujo de pago.',
    faq: [{ question: '¿Se puede ampliar después?', answer: 'Sí, si la primera versión deja una estructura preparada y se priorizan las siguientes necesidades.' }],
    links: [{ href: '/tiendas-online', label: 'Ver tiendas online' }, { href: '/tiendas-online-catamarca', label: 'Tiendas online en Catamarca' }],
    cta: { href: '/contacto', label: 'Consultar una tienda' },
  }),
  draft({
    slug: 'tienda-online-vs-tiendanube',
    path: '/blog/tienda-online-vs-tiendanube',
    title: 'Tienda online vs. Tiendanube: cómo decidir',
    description: 'Criterios para comparar una tienda online a medida con una plataforma estándar como Tiendanube.',
    quickAnswer: 'La decisión depende del control, las integraciones, la velocidad de salida, el mantenimiento y la complejidad del proceso de venta.',
    sections: [
      { heading: 'Cuándo una plataforma estándar puede alcanzar', paragraphs: ['Si el catálogo y el flujo de venta son simples, una plataforma existente puede reducir el trabajo inicial y facilitar la administración.'] },
      { heading: 'Cuándo evaluar un desarrollo propio', paragraphs: ['Si hay reglas, integraciones o procesos que no encajan, conviene analizar cuánto valor aporta una solución más específica.'] },
    ],
    example: 'Una tienda con catálogo estándar puede priorizar velocidad; una operación con stock y procesos particulares debe comparar el costo de adaptar cada alternativa.',
    faq: [{ question: '¿Cuál es mejor?', answer: 'No hay una respuesta universal: se debe comparar la necesidad concreta y el costo total de cada opción.' }],
    links: [{ href: '/tiendas-online', label: 'Tiendas online' }, { href: '/sistemas-a-medida', label: 'Sistemas a medida' }],
    cta: { href: '/contacto', label: 'Comparar alternativas' },
  }),
  draft({
    slug: 'como-empezar-a-vender-online',
    path: '/blog/como-empezar-a-vender-online',
    title: 'Cómo empezar a vender online',
    description: 'Pasos prácticos para preparar una primera versión de un canal de venta online.',
    quickAnswer: 'Empezá por definir qué vendés, a quién, cómo cobrás, cómo entregás y qué información necesita una persona para comprar.',
    sections: [
      { heading: 'Definir una oferta posible', paragraphs: ['Elegir productos, categorías y condiciones claras ayuda a evitar una tienda difícil de mantener.'] },
      { heading: 'Probar el recorrido completo', paragraphs: ['Antes de promocionar, conviene probar consulta, pedido, cobro, confirmación y entrega como si fueras un cliente.'] },
    ],
    example: 'Un emprendimiento puede lanzar una selección de productos y medir consultas antes de cargar todo su inventario.',
    faq: [{ question: '¿Necesito una tienda completa desde el primer día?', answer: 'No. Una primera versión acotada puede servir para validar el proceso y aprender.' }],
    links: [{ href: '/tiendas-online', label: 'Ver tiendas online' }, { href: '/contacto', label: 'Hablar sobre ventas online' }],
    cta: { href: '/contacto', label: 'Planificar el lanzamiento' },
  }),
  draft({
    slug: 'como-administrar-stock-tienda-online',
    path: '/blog/como-administrar-stock-tienda-online',
    title: 'Cómo administrar el stock de una tienda online',
    description: 'Buenas prácticas para mantener el stock online alineado con la operación real.',
    quickAnswer: 'El stock debe tener una fuente clara, reglas para actualizarlo y una rutina para revisar diferencias entre pedidos y existencias.',
    sections: [
      { heading: 'Definir qué significa disponible', paragraphs: ['No siempre alcanza con contar unidades: hay reservas, productos en tránsito, variantes y pedidos pendientes.'] },
      { heading: 'Reducir diferencias', paragraphs: ['Registrar movimientos y revisar excepciones permite detectar errores antes de prometer un producto que no está disponible.'] },
    ],
    example: 'Una tienda de indumentaria necesita distinguir talle y color, no solo el total de prendas.',
    faq: [{ question: '¿Una planilla alcanza?', answer: 'Puede alcanzar en una operación pequeña, pero se debe revisar si el volumen y la cantidad de canales siguen siendo manejables.' }],
    links: [{ href: '/tiendas-online', label: 'Tiendas online' }, { href: '/sistemas-a-medida', label: 'Sistemas a medida' }],
    cta: { href: '/contacto', label: 'Revisar una operación de stock' },
  }),
  draft({
    slug: 'como-integrar-mercado-pago',
    path: '/blog/como-integrar-mercado-pago',
    title: 'Cómo integrar Mercado Pago en una tienda online',
    description: 'Qué hay que definir antes de integrar Mercado Pago en un flujo de venta online.',
    quickAnswer: 'La integración requiere definir el flujo de compra, los estados de pago, las notificaciones, los reintentos y la experiencia posterior al pago.',
    sections: [
      { heading: 'El pago no es solo un botón', paragraphs: ['Hay que contemplar pagos aprobados, pendientes, rechazados, devoluciones y la confirmación que recibe el negocio.'] },
      { heading: 'Seguridad y pruebas', paragraphs: ['Las credenciales deben vivir en el entorno seguro correspondiente y el flujo debe probarse con escenarios controlados antes de publicar.'] },
    ],
    example: 'Una tienda debe saber qué ocurre si el pago queda pendiente y si el pedido se reserva o no hasta recibir confirmación.',
    faq: [{ question: '¿Siempre conviene integrarlo?', answer: 'Depende del volumen, la plataforma y la forma en que el negocio quiere cobrar.' }],
    links: [{ href: '/tiendas-online', label: 'Ver tiendas online' }, { href: '/contacto', label: 'Consultar una integración' }],
    cta: { href: '/contacto', label: 'Revisar un flujo de cobro' },
  }),
  draft({
    slug: 'cuando-conviene-sistema-a-medida',
    path: '/blog/cuando-conviene-sistema-a-medida',
    title: '¿Cuándo conviene hacer un sistema a medida?',
    description: 'Señales para evaluar un sistema propio en lugar de seguir acumulando soluciones separadas.',
    quickAnswer: 'Conviene evaluarlo cuando el proceso es repetitivo, las herramientas no encajan y el costo de seguir trabajando manualmente ya es visible.',
    sections: [
      { heading: 'No todo necesita software propio', paragraphs: ['Una herramienta estándar puede ser suficiente si resuelve el proceso sin adaptaciones costosas ni pérdida de información.'] },
      { heading: 'Empezar por un problema', paragraphs: ['Un sistema a medida debe atacar una prioridad concreta, con una primera etapa que se pueda probar y revisar.'] },
    ],
    example: 'Si un negocio repite la misma carga de datos en tres planillas, puede analizar si centralizar ese proceso aporta valor.',
    faq: [{ question: '¿Hay que automatizar todo?', answer: 'No. Conviene automatizar lo que tiene una prioridad clara y se puede definir con precisión.' }],
    links: [{ href: '/sistemas-a-medida', label: 'Sistemas a medida' }, { href: '/crm', label: 'CRM' }],
    cta: { href: '/contacto', label: 'Analizar un proceso' },
  }),
  draft({
    slug: 'sistema-de-gestion-vs-excel',
    path: '/blog/sistema-de-gestion-vs-excel',
    title: 'Sistema de gestión vs. Excel: qué evaluar',
    description: 'Diferencias entre una planilla y un sistema de gestión para decidir con datos.',
    quickAnswer: 'Excel puede ser útil para empezar, pero un sistema aporta reglas, permisos, historial y una fuente compartida cuando la operación crece.',
    sections: [
      { heading: 'Cuándo una planilla sigue siendo útil', paragraphs: ['Para análisis puntuales o procesos pequeños, una planilla puede ser flexible y suficiente si se mantiene ordenada.'] },
      { heading: 'Cuándo aparecen límites', paragraphs: ['Los problemas suelen aparecer con múltiples usuarios, versiones duplicadas, permisos, stock y necesidad de historial.'] },
    ],
    example: 'Una caja operada por varias personas necesita saber quién registró cada movimiento y cuál es el estado actual.',
    faq: [{ question: '¿Hay que abandonar Excel de inmediato?', answer: 'No. Se puede identificar qué proceso conviene mantener y cuál necesita una herramienta diferente.' }],
    links: [{ href: '/sistemas-a-medida', label: 'Ver sistemas a medida' }, { href: '/crm', label: 'Ver CRM' }],
    cta: { href: '/contacto', label: 'Comparar opciones de gestión' },
  }),
  draft({
    slug: 'que-es-un-crm',
    path: '/blog/que-es-un-crm',
    title: '¿Qué es un CRM y para qué sirve?',
    description: 'Explicación simple de qué es un CRM y qué problemas puede ayudar a ordenar.',
    quickAnswer: 'Un CRM es una herramienta para reunir información de clientes y oportunidades, registrar interacciones y dar seguimiento al trabajo comercial.',
    sections: [
      { heading: 'Qué información puede reunir', paragraphs: ['Contactos, consultas, oportunidades, tareas, ventas y notas pueden formar parte de una vista común del proceso comercial.'] },
      { heading: 'Qué no hace un CRM por sí solo', paragraphs: ['Una herramienta no reemplaza un proceso claro ni una rutina de uso. El valor aparece cuando el equipo registra y consulta información útil.'] },
    ],
    example: 'En lugar de buscar una conversación en distintos chats, un equipo puede registrar el estado de una oportunidad y su próximo paso.',
    faq: [{ question: '¿CRM es lo mismo que una agenda?', answer: 'No necesariamente. Un CRM puede incluir contactos, pero también seguimiento, estados, tareas e historial.' }],
    links: [{ href: '/crm', label: 'Ver servicio CRM' }, { href: '/portfolio/crm-retail', label: 'Ver demo de CRM retail' }],
    cta: { href: '/contacto', label: 'Consultar por un CRM' },
  }),
  draft({
    slug: 'cuando-necesita-una-empresa-un-crm',
    path: '/blog/cuando-necesita-una-empresa-un-crm',
    title: '¿Cuándo necesita una empresa un CRM?',
    description: 'Señales prácticas para saber si una empresa ya necesita ordenar su seguimiento comercial.',
    quickAnswer: 'Un CRM empieza a ser útil cuando se pierden consultas, varias personas necesitan la misma información o no se conoce el estado de las oportunidades.',
    sections: [
      { heading: 'Señales frecuentes', paragraphs: ['Clientes sin seguimiento, tareas olvidadas, información repetida y reportes armados a mano muestran que el proceso puede necesitar una herramienta.'] },
      { heading: 'Elegir el alcance correcto', paragraphs: ['No todas las empresas necesitan los mismos módulos. Conviene comenzar con el proceso que genera más fricción.'] },
    ],
    example: 'Un equipo pequeño puede empezar registrando consultas y próximos pasos antes de sumar reportes o automatizaciones.',
    faq: [{ question: '¿Una empresa chica puede usar CRM?', answer: 'Sí, si la herramienta es simple y resuelve una necesidad concreta sin agregar trabajo innecesario.' }],
    links: [{ href: '/crm', label: 'Ver CRM' }, { href: '/sistemas-a-medida', label: 'Sistemas a medida' }],
    cta: { href: '/contacto', label: 'Revisar una necesidad comercial' },
  }),
  draft({
    slug: 'crm-a-medida-vs-crm-estandar',
    path: '/blog/crm-a-medida-vs-crm-estandar',
    title: 'CRM a medida vs. CRM estándar',
    description: 'Cómo comparar un CRM estándar con un desarrollo adaptado a los procesos de una empresa.',
    quickAnswer: 'Un CRM estándar ofrece una base rápida; uno a medida puede encajar mejor cuando las reglas del negocio son específicas y justifican el trabajo adicional.',
    sections: [
      { heading: 'Ventajas de una solución estándar', paragraphs: ['Puede acelerar la puesta en marcha, ofrecer prácticas conocidas y reducir el trabajo inicial de definición.'] },
      { heading: 'Ventajas de una solución a medida', paragraphs: ['Permite modelar procesos particulares, aunque requiere más definición, desarrollo y mantenimiento.'] },
    ],
    example: 'Si una empresa necesita una combinación muy específica de stock, ventas y permisos, puede comparar adaptar un producto o construir una etapa propia.',
    faq: [{ question: '¿Cómo se toma la decisión?', answer: 'Comparando procesos, costos totales, tiempo de adopción, integraciones y capacidad de mantenimiento.' }],
    links: [{ href: '/crm', label: 'Ver CRM' }, { href: '/sistemas-a-medida', label: 'Ver sistemas a medida' }],
    cta: { href: '/contacto', label: 'Comparar alternativas' },
  }),
];

module.exports = { ARTICLES };
